-- Generated geography data; existing codes are preserved for saved records.
insert into public.districts(code,name_en,name_mr) values
('dharashiv','Dharashiv','धाराशिव'),
('solapur','Solapur','सोलापूर'),
('beed','Beed','बीड'),
('sangli','Sangli','सांगली'),
('latur','Latur','लातूर')
on conflict(code) do update set name_en=excluded.name_en,name_mr=excluded.name_mr;

insert into public.talukas(code,district_code,name_en,name_mr) values
('bhum','dharashiv','Bhum','भूम'),
('dharashiv','dharashiv','Dharashiv','धाराशिव'),
('kalamb','dharashiv','Kalamb','कळंब'),
('lohara','dharashiv','Lohara','लोहारा'),
('umarga','dharashiv','Omarga','उमरगा'),
('paranda','dharashiv','Paranda','परंडा'),
('tuljapur','dharashiv','Tuljapur','तुळजापूर'),
('washi','dharashiv','Washi','वाशी'),
('akkalkot','solapur','Akkalkot','अक्कलकोट'),
('barshi','solapur','Barshi','बार्शी'),
('karmala','solapur','Karmala','करमाळा'),
('madha','solapur','Madha','माढा'),
('malshiras','solapur','Malshiras','माळशिरस'),
('mangalwedha','solapur','Mangalvedhe','मंगळवेढे'),
('mohol','solapur','Mohol','मोहोळ'),
('pandharpur','solapur','Pandharpur','पंढरपूर'),
('sangola','solapur','Sangole','सांगोले'),
('solapur_north','solapur','Solapur North','उत्तर सोलापूर'),
('solapur_south','solapur','Solapur South','दक्षिण सोलापूर'),
('ambajogai','beed','Ambejogai','आंबेजोगाई'),
('ashti','beed','Ashti','आष्टी'),
('beed','beed','Beed','बीड'),
('dharur','beed','Dharur','धारूर'),
('georai','beed','Georai','गेवराई'),
('kaij','beed','Kaij','केज'),
('majalgaon','beed','Majalgaon','माजलगाव'),
('parli_vaijnath','beed','Parli','परळी'),
('patoda','beed','Patoda','पाटोदा'),
('shirur_kasar','beed','Shirur (Kasar)','शिरूर (कासार)'),
('wadwani','beed','Wadwani','वडवणी'),
('atpadi','sangli','Atpadi','आटपाडी'),
('jat','sangli','Jat','जत'),
('kadegaon','sangli','Kadegaon','कडेगाव'),
('kavathemahankal','sangli','Kavathemahankal','कवठेमहांकाळ'),
('khanapur','sangli','Khanapur','खानापूर'),
('miraj','sangli','Miraj','मिरज'),
('palus','sangli','Palus','पलुस'),
('shirala','sangli','Shirala','शिराळा'),
('tasgaon','sangli','Tasgaon','तासगाव'),
('walwa','sangli','Walwa','वाळवा'),
('ahmadpur','latur','Ahmadpur','अहमदपूर'),
('ausa','latur','Ausa','औसा'),
('chakur','latur','Chakur','चाकूर'),
('deoni','latur','Deoni','देवनी'),
('jalkot','latur','Jalkot','जलकोट'),
('latur','latur','Latur','लातूर'),
('nilanga','latur','Nilanga','निलंगा'),
('renapur','latur','Renapur','रेनापूर'),
('shirur_anantpal','latur','Shirur Anantpal','शिरूर अनंतपाळ'),
('udgir','latur','Udgir','उदगीर')
on conflict(code) do update set district_code=excluded.district_code,name_en=excluded.name_en,name_mr=excluded.name_mr;
