import Link from 'next/link';
import {notFound} from 'next/navigation';
import {z} from 'zod';
import type {ReactNode} from 'react';
import {requireIdentity} from '@/server/session';
import {callRpc} from '@/server/database';
import {AdminAction} from '@/components/AdminAction';
import {AdminAadhaar} from '@/components/AdminAadhaar';
import {AdminBulkButton} from '@/components/AdminBulkButton';
import {formatRupees} from '@/shared/constants';
import type {AdminRecord} from '@/features/admin/schema';
const date=(value:string)=>new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'});
const words=(value?:string)=>value?value.replaceAll('_',' '):'—';
function Fields({items}:{items:[string,ReactNode][]}){return <dl className="admin-fields">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'—'}</dd></div>)}</dl>;}
export default async function RegistrationPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{tab?:string}>}){
 const actor=await requireIdentity(['manager','super_admin']);const {id}=await params;if(!z.uuid().safeParse(id).success)notFound();
 const data=await callRpc<AdminRecord|null>('get_admin_record',{p_actor_id:actor.id,p_registration_id:id});if(!data)notFound();
 const superAdmin=actor.roles.includes('super_admin');const raw=await searchParams;const tab=['profile','payments','activity'].includes(raw.tab||'')?raw.tab!:'profile';
 const events=[
  {id:'saved',at:data.createdAt,label:'Registration saved and consent recorded',detail:data.employee||'Self registration'},
  ...data.orders.map(order=>({id:order.id,at:order.createdAt,label:'Payment order created',detail:order.providerOrderId})),
  ...(data.completedAt?[{id:'completed',at:data.completedAt,label:'Payment verified and membership created',detail:data.membership}]:[]),
  ...(data.cash?[{id:'cash',at:data.cash.receivedAt,label:'Employee cash receipt recorded',detail:formatRupees(data.cash.amountPaise)}]:[]),
  ...(data.archivedAt?[{id:'archived',at:data.archivedAt,label:'Moved to Trash',detail:data.archivedBy}]:[]),
 ].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));
 return <><Link className="admin-back" href={'/dashboard/admin?section='+(data.archivedAt?'trash':'registrations')}>← Back to {data.archivedAt?'Trash':'registrations'}</Link><header className="admin-page-heading"><div><span className="admin-kicker">Registration / {data.reference}</span><h1>{data.name}</h1><p>{data.mobile} · {data.village}, {words(data.district)}</p></div><div className="admin-record-heading-actions">{data.farmerId&&<Link className="admin-button admin-button-secondary" href={'/dashboard/farmers/'+data.farmerId}>Edit farmer profile</Link>}{superAdmin&&<AdminBulkButton ids={[id]} action={data.archivedAt?'restore':'trash'} label={data.archivedAt?'Restore record':'Move to Trash'}/>}</div></header>
 {data.archivedAt&&<p className="admin-alert">This record is in Trash. Moved by {data.archivedBy} on {date(data.archivedAt)}. Reason: {data.archiveReason}</p>}
 <nav className="admin-record-tabs" aria-label="Registration details">{['profile','payments','activity'].map(item=><Link key={item} href={'/dashboard/admin/registrations/'+id+'?tab='+item} aria-current={tab===item?'page':undefined}>{item==='profile'?'Profile & form':item==='payments'?'Payments':'Activity'}</Link>)}</nav>
 <div className="admin-record-layout"><div>
 {tab==='profile'&&<><section className="admin-record-panel"><header><h2>Personal information</h2><p>वैयक्तिक माहिती · Submitted registration details</p></header><Fields items={[["Full name / पूर्ण नाव",data.name],["Mobile number / मोबाईल",data.mobile],["Date of birth / जन्मतारीख",data.dateOfBirth],["Village / गाव",data.village],["District / जिल्हा",words(data.district)],["Taluka / तालुका",words(data.taluka)],["Income source / उत्पन्नाचे साधन",words(data.incomeSource)],["Cluster type / समूह",words(data.clusterType)]]}/>{superAdmin&&<AdminAadhaar registrationId={id} lastFour={data.aadhaarLastFour}/>}</section>
 <section className="admin-record-panel"><header><h2>Farm & plot information</h2><p>शेत माहिती · {data.plots.length} submitted plot{data.plots.length===1?'':'s'}</p></header>{data.plots.length?data.plots.map((plot,index)=><div key={plot.id} className="admin-payment-card"><h3>Plot {index+1} · {plot.plotNo}</h3><Fields items={[["Plot / survey number",plot.plotNo],["Area (acres)",plot.areaAcres],["Crop name",plot.cropName],["Irrigation source",words(plot.irrigationSource)]]}/></div>):<p className="admin-payment-card">No plot details are available for this record.</p>}</section>
 <section className="admin-record-panel"><header><h2>Account, referral & consent</h2><p>Registration context and attribution</p></header><Fields items={[["Account status",words(data.accountStatus)],["Password","Protected by a one-way hash; cannot be viewed"],["Referral code",data.referralCode||'No referral supplied'],["Commission snapshot",(data.commissionBasisPoints/100)+'%'],["Onboarded by",data.employee||'Self registration'],["Registration channel",words(data.channel)],["Consent",data.consentGiven?'Given at registration':'Not given'],["Consent recorded",date(data.createdAt)]]}/></section>
 <section className="admin-record-panel"><header><h2>Payment & cash declaration</h2></header><Fields items={[["Payment mode",words(data.paymentMode)],["Membership fee",formatRupees(data.amountPaise)],["Employee received cash",data.cash?'Yes':'No'],["Cash amount",data.cash?formatRupees(data.cash.amountPaise):'—'],["Cash collected at",data.cash?date(data.cash.receivedAt):'—'],["Cash note",data.cash?.note||'—']]}/></section></>}
 {tab==='payments'&&<><section className="admin-record-panel"><header><h2>Provider payment history</h2><p>Verify an existing payment against Razorpay.</p></header><div className="admin-payment-card"><AdminAction label="Check provider status" method="POST" endpoint="/api/admin/reconcile" body={{registrationId:id}}/></div>{data.orders.length?data.orders.map(order=><div className="admin-payment-card" key={order.id}><h3>{order.providerOrderId}</h3><Fields items={[["Internal order ID",order.id],["Expected amount",formatRupees(order.amountPaise)],["Order status",words(order.status)],["Created",date(order.createdAt)],["Paid at",order.paidAt?date(order.paidAt):'Not confirmed']]}/>{order.payments.length?order.payments.map(payment=><div className="admin-alert" key={payment.paymentId}><strong>{payment.paymentId}</strong><br/>{formatRupees(payment.amountPaise)} · {words(payment.status)}{payment.capturedAt?' · '+date(payment.capturedAt):''}</div>):<p>No verified captured payment recorded yet.</p>}</div>):<p className="admin-payment-card">No provider order is bound yet. An uncertain checkout must be reconciled before any replacement is considered.</p>}</section></>}
 {tab==='activity'&&<section className="admin-record-panel"><header><h2>Registration lifecycle</h2><p>Recorded milestones for this registration</p></header><ol className="admin-timeline">{events.map(event=><li key={event.id}>{event.label}<small>{date(event.at)} · {event.detail}</small></li>)}</ol><div className="admin-payment-card"><Link className="admin-text-button" href="/dashboard/admin?section=audit">Open administrative activity log →</Link></div></section>}
 </div><aside className="admin-record-summary"><h2>Record summary</h2><span className={'admin-status '+(data.status==='completed'?'positive':'neutral')}>{words(data.status)}</span><dl><div><dt>Registration reference</dt><dd>{data.reference}</dd></div><div><dt>Membership</dt><dd>{data.membership||'Awaiting verified payment'}</dd></div><div><dt>Registration fee</dt><dd>{formatRupees(data.amountPaise)}</dd></div><div><dt>Registered</dt><dd>{date(data.createdAt)}</dd></div><div><dt>Receipt</dt><dd>{data.receiptNumber||'Not issued yet'}</dd></div></dl>{data.receiptToken&&<Link className="admin-button admin-button-secondary" href={'/receipt/'+data.receiptToken}>Open receipt →</Link>}<Link className="admin-button admin-button-secondary" href={'/dashboard/admin/registrations/'+id+'?tab=payments'}>View payments →</Link></aside></div></>;
}
