import Link from 'next/link';
import Form from 'next/form';
import {AdminPageHeading} from '@/components/AdminPageHeading';
import {AdminFilterSubmit} from '@/components/AdminFilterSubmit';
import {redirect} from 'next/navigation';
import {getIdentity} from '@/server/session';
import {callRpc} from '@/server/database';
import {adminQuery,type AdminPageData} from '@/features/admin/schema';
import {navigationFor,adminListCopy,adminHref} from '@/features/admin/navigation';
import {AdminRecords} from '@/components/AdminRecords';
export const metadata={title:'Admin workspace'};
export default async function AdminPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const identity=await getIdentity();if(!identity)redirect('/login');if(!identity.roles.some(role=>['manager','super_admin'].includes(role)))redirect('/dashboard');const superAdmin=identity.roles.includes('super_admin');
 const raw=await searchParams;const saved=typeof raw.saved==='string'?({staff:'Team member created.',payout:'Completed payout recorded.',grant:'Temporary edit access granted.'} as Record<string,string>)[raw.saved]:undefined;
 const parsed=adminQuery.safeParse(raw);const query=parsed.success?parsed.data:adminQuery.parse({});
 if(!navigationFor(identity.roles).some(item=>item.id===query.section))redirect('/dashboard/admin');
 const data=await callRpc<AdminPageData>('get_admin_workspace',{p_actor_id:identity.id,p_section:query.section,p_query:query.q,p_page:query.page,p_status:query.status,p_sort:query.sort,p_from:query.from||null,p_to:query.to||null,p_size:query.size});
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
 const section=navigationFor(identity.roles).find(item=>item.id===query.section)!;const registrations=['registrations','trash'].includes(query.section);
 const action=query.section==='staff'&&superAdmin?{label:'Add team member',href:'/dashboard/admin/new/staff'}:query.section==='payouts'||query.section==='referrers'?{label:'Record payout',href:'/dashboard/admin/new/payout'}:query.section==='grants'?{label:'Grant edit access',href:'/dashboard/admin/new/grant'}:query.section==='registrations'?{label:'Add registration',href:'/register'}:null;
 const href=(page:number)=>adminHref(query.section,{q:query.q,status:query.status,sort:query.sort,from:query.from,to:query.to,size:String(query.size),page:String(page)});
 return <><AdminPageHeading title={section.label} description={section.description} context={superAdmin?"Administration":"Management operations"}>{action&&<Link className="admin-button" href={action.href}>＋ {action.label}</Link>}</AdminPageHeading>
 {saved&&<p className="admin-alert" role="status">{saved}</p>}
 {!parsed.success&&<p className="admin-alert error" role="alert">The filters were invalid. Showing the default view.</p>}
 {query.section==='overview'?<><div className="admin-metrics">{[{label:'All registrations',value:data.summary.total,link:adminHref('registrations'),caption:'Across all records'},{label:'Completed registrations',value:data.summary.completed,link:adminHref('registrations',{status:'completed'}),caption:'Payment completed'},{label:'Awaiting completion',value:data.summary.pending,link:adminHref('registrations'),caption:'Review pending payments'},{label:'New today',value:data.summary.today??0,link:adminHref('registrations',{from:today,to:today}),caption:'India Standard Time'}].map(metric=><Link className="admin-metric" href={metric.link} key={metric.label}><span>{metric.label}</span><strong>{metric.value.toLocaleString('en-IN')}</strong><small>{metric.caption} <span aria-hidden="true">↗</span></small></Link>)}</div><section className="admin-overview-actions"><div><h2>Keep operations moving</h2><p>Review payment exceptions or open a focused workspace.</p></div><div><Link className="admin-button admin-button-secondary" href={adminHref('exceptions')}>Review exceptions →</Link><Link className="admin-button admin-button-secondary" href={adminHref('staff')}>{superAdmin?'Manage team':'Review team activity'} →</Link></div></section><div className="admin-section-heading"><div><h2>Recent registrations</h2><p>The latest six records in your workspace</p></div><Link className="admin-text-button" href={adminHref('registrations')}>View all registrations →</Link></div><AdminRecords rows={data.rows} section="overview" superAdmin={superAdmin}/></>:<>
 <Form key={"filters:"+JSON.stringify(query)} className="admin-filters" action="/dashboard/admin"><input type="hidden" name="section" value={query.section}/><label className="admin-search-field"><span>Search {section.label.toLowerCase()}</span><input name="q" type="search" defaultValue={query.q} maxLength={100} placeholder={adminListCopy[query.section].search}/></label>{registrations&&<><label><span>Status</span><select name="status" defaultValue={query.status}><option value="">All statuses</option><option value="payment_pending">Payment pending</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="payment_exception">Payment exception</option></select></label><label><span>Sort</span><select name="sort" defaultValue={query.sort}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option></select></label><details className="admin-more-filters" open={Boolean(query.from||query.to||query.size!==25)}><summary>Date & page size</summary><div><label>From<input type="date" name="from" defaultValue={query.from}/></label><label>To<input type="date" name="to" defaultValue={query.to}/></label><label>Rows per page<select name="size" defaultValue={query.size}><option>25</option><option>50</option><option>100</option></select></label></div></details></>}<AdminFilterSubmit/>{(query.q||query.status||query.from||query.to||query.sort!=='newest'||query.size!==25)&&<Link className="admin-text-button" href={adminHref(query.section)}>Clear filters</Link>}</Form>
 {query.section==='trash'&&<p className="admin-alert">Moving a record to Trash hides it from active lists. It does not revoke membership or delete payment history. Select records below to restore them or permanently delete personal data. Permanent deletion requires your super-admin password; financial and audit history remains.</p>}
 <div className="admin-result-count"><span>{data.total!==undefined?`${data.total.toLocaleString('en-IN')} matching record${data.total===1?'':'s'}`:'Latest records'}</span>{query.from||query.to?<span>{query.from||'Any date'} → {query.to||'Today'}</span>:null}</div>
 <AdminRecords actorId={identity.id} returnTo={href(query.page)} key={"records:"+JSON.stringify(query)} rows={data.rows} section={query.section} superAdmin={superAdmin} matching={query.section==='registrations'&&data.total!==undefined?{count:data.total,filters:{q:query.q,status:query.status,from:query.from,to:query.to}}:undefined}/>
 <nav className="admin-pagination" aria-label="Results pages"><span>Page {query.page}{data.total!==undefined?' of '+Math.max(1,Math.ceil(data.total/query.size)):''} · {data.rows.length} shown</span><div>{query.page>1?<Link className="admin-button admin-button-secondary" href={href(query.page-1)}>← Previous</Link>:<span className="admin-button admin-button-secondary is-disabled">← Previous</span>}{data.hasNext?<Link className="admin-button admin-button-secondary" href={href(query.page+1)}>Next →</Link>:<span className="admin-button admin-button-secondary is-disabled">Next →</span>}</div></nav>
 </>}</>;
}
