import { z } from 'zod';
export const sections=['overview','registrations','staff','referrers','payouts','exceptions','grants','audit','trash'] as const;
export const adminQuery=z.object({section:z.enum(sections).default('overview'),q:z.string().trim().max(100).default(''),page:z.coerce.number().int().min(1).max(10000).default(1),status:z.enum(['','payment_pending','processing','completed','payment_exception']).default(''),sort:z.enum(['newest','oldest','name']).default('newest'),from:z.union([z.iso.date(),z.literal('')]).default(''),to:z.union([z.iso.date(),z.literal('')]).default(''),size:z.coerce.number().refine(n=>[25,50,100].includes(n)).default(25)}).refine(v=>!v.from||!v.to||v.from<=v.to,{message:'Start date must be before end date.'});
export const deleteFilters=z.object({q:z.string().trim().max(100).default(''),status:z.enum(['','payment_pending','processing','completed','payment_exception']).default(''),from:z.union([z.iso.date(),z.literal('')]).default(''),to:z.union([z.iso.date(),z.literal('')]).default('')}).strict().refine(v=>!v.from||!v.to||v.from<=v.to);
export const bulkActionSchema=z.object({ids:z.array(z.uuid()).max(100),action:z.enum(['trash','restore','purge','activate','deactivate','revoke']),reason:z.string().trim().max(300).default(''),password:z.string().max(72).optional(),allMatching:z.boolean().default(false),expectedCount:z.number().int().positive().optional(),filters:deleteFilters.optional()}).strict().refine(v=>v.allMatching?v.action==='trash'&&v.ids.length===0&&v.expectedCount!==undefined&&v.filters!==undefined:v.ids.length>0&&!v.filters&&!v.expectedCount,{message:'Choose records or all matching registrations.'}).refine(v=>v.action!=='trash'||v.reason.length>=3,{message:'Enter a reason for moving records to Trash.'}).refine(v=>v.action!=='purge'||Boolean(v.password),{message:'Enter your super-admin password for permanent deletion.'});
export interface AdminRow {id:string;label:string;reference?:string;status?:string;mobile?:string;actor?:string;createdAt?:string;amountPaise?:number;earnedPaise?:number;paidPaise?:number;farmerId?:string;registrationId?:string;roles?:string[];fields?:string[];expiresAt?:string;onboardedFarmers?:number;paymentId?:string;village?:string;district?:string;archivedAt?:string}
export interface AdminPageData {summary:{total:number;completed:number;pending:number;today?:number;trash?:number};rows:AdminRow[];hasNext:boolean;page:number;total?:number}
export interface RegistrationDetail {id:string;reference:string;name:string;mobileMasked:string;status:string;amountPaise:number;createdAt:string;completedAt?:string;employee?:string;referralCode?:string;paymentMode:string;farmerId?:string;membership?:string;receiptNumber?:string;receiptToken?:string;orders:{id:string;providerOrderId:string;amountPaise:number;status:string;createdAt:string;paidAt?:string;payments:{paymentId:string;amountPaise:number;status:string;capturedAt?:string}[]}[]}
export interface AdminRecord extends RegistrationDetail {mobile:string;dateOfBirth:string;village:string;district:string;taluka:string;incomeSource:string;clusterType:string;consentGiven:boolean;channel:string;commissionBasisPoints:number;accountStatus:string;aadhaarLastFour?:string;archivedAt?:string;archivedBy?:string;archiveReason?:string;cash?:{amountPaise:number;receivedAt:string;note?:string};plots:{id:string;plotNo:string;areaAcres:number;cropName:string;irrigationSource:string}[]}
