// Shared by the public cluster explorer, forms and registration validation.
// Existing cluster IDs stay stable for saved profiles.
export const CROP_CATEGORIES = [
  { id: "cereals", label: "तृणधान्ये / Cereals", crops: ["ज्वारी", "बाजरी", "मका", "गहू", "इतर लघुधान्ये"] },
  { id: "pulses", label: "कडधान्ये / Pulses", crops: ["तूर", "हरभरा", "मूग", "उडीद", "मटकी", "इतर कडधान्ये"] },
  { id: "oilseeds", label: "तेलबिया / Oilseeds", crops: ["सोयाबीन", "भुईमूग", "सूर्यफूल", "करडई", "तीळ", "इतर तेलबिया"] },
  { id: "cash", label: "नगदी व तंतू पिके / Cash & Fibre Crops", crops: ["कापूस", "ऊस", "इतर तंतू व नगदी पिके"] },
  { id: "fruits", label: "फळपिके / Fruits", crops: ["आंबा", "डाळिंब", "द्राक्ष", "केळी", "लिंबू", "पेरू", "पपई", "चिकू", "सीताफळ", "अंजीर", "बोर", "नारळ", "चिंच", "कलिंगड", "खरबूज", "इतर फळपिके"] },
  { id: "vegs", label: "भाजीपाला / Vegetables", crops: ["पालक", "मेथी", "शेपू", "कोथिंबीर", "टोमॅटो", "वांगी", "भेंडी", "मिरची", "ढोबळी मिरची", "काकडी", "दुधी भोपळा", "कारले", "भोपळा", "गवार", "शेवगा", "कोबी", "फ्लॉवर", "इतर"] },
  { id: "spices", label: "मसाला पिके / Spices", crops: ["हळद", "आले", "मिरची", "लसूण", "मेथी", "इतर मसाला पिके"] },
  { id: "flowers", label: "फुलपिके / Flowers", crops: ["व्यावसायिक फुले", "गुलाब", "झेंडू", "शेवंती", "जरबेरा", "मोगरा"] },
  { id: "medicinal", label: "औषधी व सुगंधी वनस्पती / Medicinal & Aromatic Crops", crops: ["अश्वगंधा", "शतावरी", "सफेद मुसळी", "तुळस", "कोरफड"] },
  { id: "mushroom", label: "मशरूम / Mushroom Farming", crops: ["बटन मशरूम", "ऑयस्टर मशरूम", "इतर खाद्य मशरूम"] },
  { id: "allied", label: "संलग्न कृषी व्यवसाय / Allied Agriculture", crops: ["पशु पालन- दुग्ध व्यवसाय", "शेळी पालन", "कुक्कुटपालन", "मत्स्यपालन", "मधमाशीपालन", "रेशीम उद्योग / Silk", "पशुखाद्य उत्पादन"] },
  { id: "protected", label: "संरक्षित शेती / Protected Cultivation", crops: ["Polyhouse", "Greenhouse", "Shade Net", "Net House", "Hydroponics", "Nursery / रोपवाटिका"] },
  { id: "agroforestry", label: "कृषी वनीकरण / Agroforestry", crops: ["सागवान", "बांबू", "चंदन"] },
] as const;

// Display labels are bilingual; stored crop values stay compatible with saved registrations.
type CropName = (typeof CROP_CATEGORIES)[number]["crops"][number];
export const CROP_LABELS = {
  "ज्वारी": "ज्वारी / Sorghum",
  "बाजरी": "बाजरी / Pearl Millet",
  "मका": "मका / Maize",
  "गहू": "गहू / Wheat",
  "इतर लघुधान्ये": "इतर लघुधान्ये / Other Minor Millets",
  "तूर": "तूर / Pigeon Pea",
  "हरभरा": "हरभरा / Chickpea",
  "मूग": "मूग / Green Gram",
  "उडीद": "उडीद / Black Gram",
  "मटकी": "मटकी / Moth Bean",
  "इतर कडधान्ये": "इतर कडधान्ये / Other Pulses",
  "सोयाबीन": "सोयाबीन / Soybean",
  "भुईमूग": "भुईमूग / Groundnut",
  "सूर्यफूल": "सूर्यफूल / Sunflower",
  "करडई": "करडई / Safflower",
  "तीळ": "तीळ / Sesame",
  "इतर तेलबिया": "इतर तेलबिया / Other Oilseeds",
  "कापूस": "कापूस / Cotton",
  "ऊस": "ऊस / Sugarcane",
  "इतर तंतू व नगदी पिके": "इतर तंतू व नगदी पिके / Other Fibre & Cash Crops",
  "आंबा": "आंबा / Mango",
  "डाळिंब": "डाळिंब / Pomegranate",
  "द्राक्ष": "द्राक्ष / Grapes",
  "केळी": "केळी / Banana",
  "लिंबू": "लिंबू / Lemon",
  "पेरू": "पेरू / Guava",
  "पपई": "पपई / Papaya",
  "चिकू": "चिकू / Sapodilla",
  "सीताफळ": "सीताफळ / Custard Apple",
  "अंजीर": "अंजीर / Fig",
  "बोर": "बोर / Indian Jujube",
  "नारळ": "नारळ / Coconut",
  "चिंच": "चिंच / Tamarind",
  "कलिंगड": "कलिंगड / Watermelon",
  "खरबूज": "खरबूज / Muskmelon",
  "इतर फळपिके": "इतर फळपिके / Other Fruits",
  "पालक": "पालक / Spinach",
  "मेथी": "मेथी / Fenugreek",
  "शेपू": "शेपू / Dill",
  "कोथिंबीर": "कोथिंबीर / Coriander",
  "टोमॅटो": "टोमॅटो / Tomato",
  "वांगी": "वांगी / Brinjal",
  "भेंडी": "भेंडी / Okra",
  "मिरची": "मिरची / Chilli",
  "ढोबळी मिरची": "ढोबळी मिरची / Capsicum",
  "काकडी": "काकडी / Cucumber",
  "दुधी भोपळा": "दुधी भोपळा / Bottle Gourd",
  "कारले": "कारले / Bitter Gourd",
  "भोपळा": "भोपळा / Pumpkin",
  "गवार": "गवार / Cluster Bean",
  "शेवगा": "शेवगा / Drumstick",
  "कोबी": "कोबी / Cabbage",
  "फ्लॉवर": "फ्लॉवर / Cauliflower",
  "इतर": "इतर / Other Vegetables",
  "हळद": "हळद / Turmeric",
  "आले": "आले / Ginger",
  "लसूण": "लसूण / Garlic",
  "इतर मसाला पिके": "इतर मसाला पिके / Other Spices",
  "व्यावसायिक फुले": "व्यावसायिक फुले / Commercial Flowers",
  "गुलाब": "गुलाब / Rose",
  "झेंडू": "झेंडू / Marigold",
  "शेवंती": "शेवंती / Chrysanthemum",
  "जरबेरा": "जरबेरा / Gerbera",
  "मोगरा": "मोगरा / Arabian Jasmine",
  "अश्वगंधा": "अश्वगंधा / Ashwagandha",
  "शतावरी": "शतावरी / Shatavari",
  "सफेद मुसळी": "सफेद मुसळी / Safed Musli",
  "तुळस": "तुळस / Holy Basil",
  "कोरफड": "कोरफड / Aloe Vera",
  "बटन मशरूम": "बटन मशरूम / Button Mushroom",
  "ऑयस्टर मशरूम": "ऑयस्टर मशरूम / Oyster Mushroom",
  "इतर खाद्य मशरूम": "इतर खाद्य मशरूम / Other Edible Mushrooms",
  "पशु पालन- दुग्ध व्यवसाय": "पशुपालन - दुग्ध व्यवसाय / Livestock & Dairy Farming",
  "शेळी पालन": "शेळी पालन / Goat Farming",
  "कुक्कुटपालन": "कुक्कुटपालन / Poultry Farming",
  "मत्स्यपालन": "मत्स्यपालन / Fish Farming",
  "मधमाशीपालन": "मधमाशीपालन / Beekeeping",
  "रेशीम उद्योग / Silk": "रेशीम उद्योग / Sericulture (Silk Farming)",
  "पशुखाद्य उत्पादन": "पशुखाद्य उत्पादन / Animal Feed Production",
  "Polyhouse": "पॉलीहाऊस / Polyhouse",
  "Greenhouse": "हरितगृह / Greenhouse",
  "Shade Net": "शेड नेट / Shade Net",
  "Net House": "जाळीगृह / Net House",
  "Hydroponics": "मातीविना जलशेती / Hydroponics",
  "Nursery / रोपवाटिका": "रोपवाटिका / Nursery",
  "सागवान": "सागवान / Teak",
  "बांबू": "बांबू / Bamboo",
  "चंदन": "चंदन / Sandalwood",
} satisfies Record<CropName, string>;

export const CLUSTER_OPTIONS = CROP_CATEGORIES.map(category => category.id);
const cropNames = new Set<string>(CROP_CATEGORIES.flatMap(category => [...category.crops]));
export function isCatalogCrop(value: string): boolean {
  return cropNames.has(value);
}
