import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
const psql=process.env.PSQL_PATH||'psql';
const database=process.env.TEST_DATABASE_URL;
if(!database||!['localhost','127.0.0.1','[::1]'].includes(new URL(database).hostname))throw Error('Only an isolated loopback test database is allowed.');
function query(sql){return new Promise((resolve,reject)=>{const child=spawn(psql,['-X','-A','-t','-q','-v','ON_ERROR_STOP=1','--dbname',database],{windowsHide:true});let output='';let error='';child.stdout.on('data',v=>output+=v);child.stderr.on('data',v=>error+=v);child.on('error',reject);child.on('exit',code=>code?reject(Error(error)):resolve(output.trim()));child.stdin.end('set role service_role;'+sql);});}
const literal=value=>value===null?'NULL':typeof value==='number'?String(value):typeof value==='boolean'?String(value):Array.isArray(value)?'ARRAY['+value.map(literal).join(',')+']':"'"+String(typeof value==='object'?JSON.stringify(value):value).replaceAll("'","''")+"'";
const server=createServer(async(request,response)=>{try{if(request.headers.apikey!=='isolated-test-key'){response.writeHead(403);response.end('{}');return;}const name=request.url.split('/').pop();if(!/^[a-z_]+$/.test(name))throw Error('Invalid RPC');let raw='';for await(const part of request)raw+=part;const params=JSON.parse(raw);if(Object.keys(params).some(key=>!/^p_[a-z_]+$/.test(key)))throw Error('Invalid argument');const sql='select to_jsonb(public.'+name+'('+Object.entries(params).map(([key,value])=>key+'=>'+literal(value)+(key==='p_ids'?'::uuid[]':'')).join(',')+'));';const result=await query(sql);if(['change_account_password','revoke_account_session'].includes(name)){response.writeHead(204);response.end();return;}response.setHeader('Content-Type','application/json');response.end(result||'null');}catch(error){const message=['Sign in to add another membership','Existing member details must match','Select all memberships before permanent deletion','Registration was permanently deleted','One or more fields are not authorized','Registration fee changed','Password confirmation required','Incorrect confirmation password','Selection changed','Not authorized'].find(value=>error instanceof Error&&error.message.includes('ERROR:  '+value))||'Test database RPC failed';response.writeHead(400,{'Content-Type':'application/json'});response.end(JSON.stringify({code:'P0001',message}));}});
server.listen(Number(process.env.RPC_BRIDGE_PORT??55434),'127.0.0.1',()=>console.log('Isolated RPC bridge ready on port '+server.address().port));
