"use client";
import {useRef,useState} from 'react';
import {requestJson} from '@/shared/request';
import {formatRupees} from '@/shared/constants';
interface Option{id:string;label:string;availablePaise?:number}
export function AdminLookup({name,kind,label,employeeId,onSelect}:{name:string;kind:string;label:string;employeeId?:string;onSelect?:(id:string)=>void}){
 const [q,setQ]=useState('');const [items,setItems]=useState<Option[]>([]);const [selected,setSelected]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const running=useRef(false);const version=useRef(0);
 async function search(){if(running.current||q.trim().length<2)return;running.current=true;const requestVersion=version.current;setBusy(true);setMessage('');try{const params=new URLSearchParams({kind,q,...(employeeId?{employeeId}:{})});const r=await requestJson<{data:Option[]}>('/api/admin/lookup?'+params,undefined,'GET');if(requestVersion!==version.current)return;setItems(r.data);setSelected('');onSelect?.('');setMessage(r.data.length?'Choose a result below.':'No matching records found.');}catch(e){setMessage(e instanceof Error?e.message:'Search unavailable.');}finally{running.current=false;setBusy(false);}}
 const balance=items.find(x=>x.id===selected)?.availablePaise;
 return <div className="lookup"><label>{label}<input type="search" value={q} maxLength={100} placeholder="Name, full mobile or reference" onChange={e=>{version.current++;setQ(e.target.value);setItems([]);setSelected('');setMessage('');onSelect?.('');}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void search();}}}/></label><button type="button" className="admin-button admin-button-secondary" disabled={busy||q.trim().length<2||(kind==='farmer'&&!employeeId)} onClick={()=>void search()}>{busy?'Searching…':'Search'}</button><label>Select {label.toLowerCase()}<select name={name} required value={selected} onChange={e=>{setSelected(e.target.value);onSelect?.(e.target.value);}}><option value="">Select a search result</option>{items.map(item=><option key={item.id} value={item.id}>{item.label}{item.availablePaise!==undefined?' · Available '+formatRupees(item.availablePaise):''}</option>)}</select></label>{kind==='farmer'&&!employeeId&&<small>Select an employee first to find their farmers.</small>}{balance!==undefined&&<p>Available balance: <strong>{formatRupees(balance)}</strong></p>}{message&&<small role="status">{message}</small>}</div>;
}
