'use client';
import {useId,useRef,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {requestJson} from '@/shared/request';
export interface AllMatchingSelection {count:number;filters:{q:string;status:string;from:string;to:string}}
export function AdminBulkButton({ids,action,label,onDone,allMatching,entityName}:{ids:string[];action:'trash'|'restore'|'purge'|'activate'|'deactivate'|'revoke';label:string;onDone?:(message:string)=>void;allMatching?:AllMatchingSelection;entityName?:string}){
 const titleId=useId();const dialog=useRef<HTMLDialogElement>(null);const running=useRef(false);const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const count=allMatching?.count??ids.length;const needsPassword=action==='purge'||action==='trash'&&(Boolean(allMatching)||count>25);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(running.current)return;running.current=true;setBusy(true);setError('');const element=event.currentTarget;const form=new FormData(element);
  try{const result=await requestJson<{data:{changed:number}}>('/api/admin/bulk',{ids:allMatching?[]:ids,action,reason:form.get('reason')||'',...(needsPassword?{password:form.get('password')}:{}),...(allMatching?{allMatching:true,expectedCount:count,filters:allMatching.filters}:{})});dialog.current?.close();const message=`${result.data.changed} record${result.data.changed===1?'':'s'} ${({trash:'moved to Trash',restore:'restored',purge:'permanently deleted',activate:'activated',deactivate:'deactivated',revoke:'revoked'})[action]}.`;setNotice(message);onDone?.(message);router.refresh();}
  catch(e){setError(e instanceof Error?e.message:'The action could not be completed.');}finally{const input=element.elements.namedItem('password');if(input instanceof HTMLInputElement)input.value='';running.current=false;setBusy(false);}
 }
 function close(){dialog.current?.close();dialog.current?.querySelector('form')?.reset();}
 function trapFocus(event:React.KeyboardEvent<HTMLDialogElement>){
  if(event.key!=='Tab')return;
  const controls=event.currentTarget.querySelectorAll<HTMLElement>('input:not(:disabled),textarea:not(:disabled),button:not(:disabled)');
  const first=controls[0],last=controls[controls.length-1];if(!first||!last)return;
  if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}
  else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}
 }
 return <><button type="button" className={'admin-button '+(['trash','purge','deactivate','revoke'].includes(action)?'admin-button-danger':'admin-button-secondary')} disabled={!count||busy} onClick={()=>{setError('');dialog.current?.querySelector('form')?.reset();dialog.current?.showModal();}}>{label}</button><dialog ref={dialog} onKeyDown={trapFocus} aria-labelledby={titleId} className="admin-dialog" onCancel={event=>{if(busy)event.preventDefault();else dialog.current?.querySelector('form')?.reset();}}><form onSubmit={submit}><span className="admin-kicker">Confirm action</span><h2 id={titleId}>{label}{entityName?` — ${entityName}`:""}</h2><p><strong>{count.toLocaleString('en-IN')}</strong> {allMatching?'matching records across every page':'selected record'+(count===1?'':'s')} will be affected.</p>{action==='purge'?<><p>This cannot be undone. Personal details, Aadhaar and plots will be permanently removed from the database and these records will leave Trash. Login access ends. Existing receipts (including their original name), payments, memberships, referral balances and audit history remain. Pending payments do not prevent deletion. Payment and cash records remain; any payment received afterward is kept for admin review without restoring this profile.</p><label>Your super-admin password<input name="password" type="password" autoComplete="current-password" required maxLength={72}/></label></>:action==='trash'?<><p>Deleted records move to Trash and can be restored. Payments, memberships, receipts and earnings remain intact. This does not cancel an active checkout.</p><label>Reason<textarea name="reason" required minLength={3} maxLength={300} rows={3} placeholder="Why are these records being removed?"/></label>{needsPassword&&<label>Your super-admin password<input name="password" type="password" autoComplete="current-password" required maxLength={72}/><small>Password confirmation is required for more than 25 records or all matching records.</small></label>}</>:<p>{action==='restore'?'Records will return to the registration list.':action==='deactivate'?'Staff access will be disabled and existing sessions revoked.':action==='revoke'?'The selected temporary edit permissions will stop working.':'Staff access will be enabled.'}</p>}{error&&<p className="admin-alert error" role="alert">{error}</p>}<div className="admin-dialog-actions"><button className="admin-button admin-button-secondary" type="button" disabled={busy} onClick={close}>Cancel</button><button className={"admin-button "+(["trash","purge","deactivate","revoke"].includes(action)?"admin-button-danger":"")} disabled={busy}>{busy?'Saving…':'Confirm '+label.toLowerCase()}</button></div></form></dialog>{notice&&<span className="admin-inline-notice" role="status">{notice}</span>}</>;
}
