'use client';
import Link from 'next/link';
import {useRef,useState,useEffect} from 'react';
import type {AdminRow} from '@/features/admin/schema';
import {formatRupees} from '@/shared/constants';
import {adminRowsCsv} from '@/features/admin/csv';
import {AdminBulkButton,type AllMatchingSelection} from './AdminBulkButton';
export function AdminRecords({rows,section,superAdmin,matching}:{rows:AdminRow[];section:string;superAdmin:boolean;matching?:AllMatchingSelection}){
 const [allMatching,setAllMatching]=useState(false);
 const [selected,setSelected]=useState<string[]>([]);const all=useRef<HTMLInputElement>(null);
 const selectable=['registrations','trash','staff','grants'].includes(section)&&(superAdmin||section==='grants');
 useEffect(()=>{if(all.current)all.current.indeterminate=selected.length>0&&selected.length<rows.length;},[selected,rows.length]);
 function toggle(id:string){setAllMatching(false);setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);}
 function exportRows(){const blob=new Blob([adminRowsCsv(rows.filter(row=>selected.includes(row.id)))],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='ganpati-'+section+'.csv';link.click();URL.revokeObjectURL(url);}
 const clear=()=>{setSelected([]);setAllMatching(false);};
 return <section className="admin-data" aria-label={section}><div className="admin-selection-bar">{selectable?<label><input ref={all} type="checkbox" aria-label="Select all records on this page" checked={rows.length>0&&selected.length===rows.length} disabled={!rows.length} onChange={e=>{setAllMatching(false);setSelected(e.target.checked?rows.map(row=>row.id):[]);}}/>{allMatching?`All ${matching!.count.toLocaleString('en-IN')} matching records selected`:selected.length?`${selected.length} selected`:'Select page'}</label>:<span>{rows.length} records on this page</span>}{selected.length>0&&<div className="admin-bulk-actions">{section==='registrations'&&matching&&matching.count>rows.length&&selected.length===rows.length&&!allMatching&&<button className="admin-text-button" onClick={()=>setAllMatching(true)}>Select all {matching.count.toLocaleString('en-IN')} matching records</button>}{section==='registrations'&&<>{!allMatching&&<button className="admin-button admin-button-secondary" onClick={exportRows}>Export CSV</button>}<AdminBulkButton ids={selected} action="trash" label="Delete selected" allMatching={allMatching?matching:undefined} onDone={clear}/></>}{section==='trash'&&<AdminBulkButton ids={selected} action="restore" label="Restore" onDone={clear}/>} {section==='staff'&&<><AdminBulkButton ids={selected} action="activate" label="Activate" onDone={clear}/><AdminBulkButton ids={selected} action="deactivate" label="Deactivate" onDone={clear}/></>}{section==='grants'&&<AdminBulkButton ids={selected} action="revoke" label="Revoke access" onDone={clear}/>}<button className="admin-text-button" onClick={clear}>Clear selection</button></div>}</div>
 {rows.length?<div className="admin-table-scroll"><table className="admin-table"><thead><tr>{selectable&&<th className="admin-select-cell"><span className="sr-only">Select</span></th>}<th>{section==='staff'?'Team member':section==='audit'?'Activity':section==='exceptions'?'Exception':'Record'}</th><th>{section==='grants'?'Permission':'Status'}</th><th>{section==='referrers'?'Balance':section==='staff'?'Onboarding':'Details'}</th><th>{section==='referrers'?'Paid to date':'Date'}</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(row=>{
 const recordHref=['overview','registrations','trash'].includes(section)?'/dashboard/admin/registrations/'+row.id:row.registrationId?'/dashboard/admin/registrations/'+row.registrationId:null;
 return <tr key={row.id} className={selected.includes(row.id)?'is-selected':''}>{selectable&&<td className="admin-select-cell"><input aria-label={'Select '+row.label} type="checkbox" checked={selected.includes(row.id)} onChange={()=>toggle(row.id)}/></td>}<td className="admin-record-name">{recordHref?<Link href={recordHref}>{row.label}</Link>:<strong>{row.label.replaceAll('_',' ')}</strong>}<small>{row.reference||row.mobile||row.id}</small>{row.village&&<small>{row.village} · {row.district}</small>}</td><td data-label={section==='grants'?'Permission':'Status'}>{row.status&&<span className={'admin-status '+(['completed','active','processed'].includes(row.status)?'positive':['failed','payment_exception','disabled','revoked'].includes(row.status)?'negative':'neutral')}>{row.status.replaceAll('_',' ')}</span>}{row.roles&&<small>{row.roles.join(' · ').replaceAll('_',' ')}</small>}{row.fields&&<small>{row.fields.join(', ').replaceAll('_',' ')}</small>}</td><td data-label="Details">{row.amountPaise!==undefined&&<strong>{formatRupees(row.amountPaise)}</strong>}{row.earnedPaise!==undefined&&<><strong>{formatRupees(row.earnedPaise-(row.paidPaise??0))}</strong><small>Earned {formatRupees(row.earnedPaise)}</small></>}{row.onboardedFarmers!==undefined&&<strong>{row.onboardedFarmers} farmers</strong>}{row.actor&&<small>{row.actor}</small>}{row.mobile&&row.reference&&<small>{row.mobile}</small>}{row.paymentId&&<small>{row.paymentId}</small>}</td><td data-label={section==='referrers'?'Paid':'Date'}>{section==='referrers'?formatRupees(row.paidPaise??0):row.createdAt?<><time dateTime={row.createdAt}>{new Date(row.createdAt).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'})}</time><small>{new Date(row.createdAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'})}</small></>:null}{row.expiresAt&&<small>Until {new Date(row.expiresAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</small>}</td><td className="admin-row-actions">{recordHref&&<Link className="admin-text-button" href={recordHref}>View record →</Link>}{row.farmerId&&!recordHref&&<Link className="admin-text-button" href={'/dashboard/farmers/'+row.farmerId}>View farmer →</Link>}{section==='staff'&&superAdmin&&<AdminBulkButton ids={[row.id]} action={row.status==='active'?'deactivate':'activate'} label={row.status==='active'?'Deactivate':'Activate'}/>} {section==='grants'&&row.status==='active'&&<AdminBulkButton ids={[row.id]} action="revoke" label="Revoke"/>}</td></tr>;
 })}</tbody></table></div>:<div className="admin-empty"><span aria-hidden="true">◎</span><h2>No records found</h2><p>Try another search or clear your filters. New records will appear here.</p></div>}</section>;
}
