'use client';
import {useRef,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {requestJson} from '@/shared/request';
export interface AllMatchingSelection {count:number;filters:{q:string;status:string;from:string;to:string}}
export function AdminBulkButton({ids,action,label,onDone,allMatching}:{ids:string[];action:'trash'|'restore'|'activate'|'deactivate'|'revoke';label:string;onDone?:()=>void;allMatching?:AllMatchingSelection}){
 const dialog=useRef<HTMLDialogElement>(null);const running=useRef(false);const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const count=allMatching?.count??ids.length;const needsPassword=action==='trash'&&(Boolean(allMatching)||count>25);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(running.current)return;running.current=true;setBusy(true);setError('');const element=event.currentTarget;const form=new FormData(element);
  try{const result=await requestJson<{data:{changed:number}}>('/api/admin/bulk',{ids:allMatching?[]:ids,action,reason:form.get('reason')||'',...(needsPassword?{password:form.get('password')}:{}),...(allMatching?{allMatching:true,expectedCount:count,filters:allMatching.filters}:{})});dialog.current?.close();setNotice(`${result.data.changed} record${result.data.changed===1?'':'s'} updated.`);onDone?.();router.refresh();}
  catch(e){setError(e instanceof Error?e.message:'The action could not be completed.');}finally{const input=element.elements.namedItem('password');if(input instanceof HTMLInputElement)input.value='';running.current=false;setBusy(false);}
 }
 function close(){dialog.current?.close();dialog.current?.querySelector('form')?.reset();}
 return <><button type="button" className={'admin-button '+(['trash','deactivate','revoke'].includes(action)?'admin-button-danger':'admin-button-secondary')} disabled={!count||busy} onClick={()=>{setError('');dialog.current?.querySelector('form')?.reset();dialog.current?.showModal();}}>{label}</button><dialog ref={dialog} className="admin-dialog" onCancel={event=>{if(busy)event.preventDefault();else dialog.current?.querySelector('form')?.reset();}}><form onSubmit={submit}><span className="admin-kicker">Confirm action</span><h2>{label}</h2><p><strong>{count.toLocaleString('en-IN')}</strong> {allMatching?'matching records across every page':'selected record'+(count===1?'':'s')} will be affected.</p>{action==='trash'?<><p>Deleted records move to Trash and can be restored. Payments, memberships, receipts and earnings remain intact. This does not cancel an active checkout.</p><label>Reason<textarea name="reason" required minLength={3} maxLength={300} rows={3} placeholder="Why are these records being removed?"/></label>{needsPassword&&<label>Your super-admin password<input name="password" type="password" autoComplete="current-password" required maxLength={72}/><small>Password confirmation is required for more than 25 records or all matching records.</small></label>}</>:<p>{action==='restore'?'Records will return to the registration list.':action==='deactivate'?'Staff access will be disabled and existing sessions revoked.':action==='revoke'?'The selected temporary edit permissions will stop working.':'Staff access will be enabled.'}</p>}{error&&<p className="admin-alert error" role="alert">{error}</p>}<div className="admin-dialog-actions"><button className="admin-button admin-button-secondary" type="button" disabled={busy} onClick={close}>Cancel</button><button className="admin-button" disabled={busy}>{busy?'Saving…':'Confirm '+label.toLowerCase()}</button></div></form></dialog>{notice&&<span className="admin-inline-notice" role="status">{notice}</span>}</>;
}
