'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {adminHref} from '@/features/admin/navigation';
import {useRouter} from 'next/navigation';
import {PersonNameInput} from './PersonNameInput';
import {digitPaste,digitBeforeInput} from '@/shared/digit-input';
import {AdminLookup} from './AdminLookup';
import {requestJson,RequestError} from '@/shared/request';
import {readPendingPayout,pendingPayoutSchema,type PendingPayout} from '@/features/admin/pending-payout';
export function AdminConsole({kind,accountId}:{kind:'staff'|'payout'|'grant';accountId:string}){
 const router=useRouter();const running=useRef(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [employeeId,setEmployeeId]=useState('');
 const storageKey='ga_pending_payout:'+accountId;const [pending,setPending]=useState<PendingPayout|null>(null);const [ready,setReady]=useState(kind!=='payout');
 useEffect(()=>{if(kind!=='payout')return;const frame=requestAnimationFrame(()=>{try{setPending(readPendingPayout(sessionStorage.getItem(storageKey)));setReady(true);}catch{setError('Saved payout recovery data could not be read. Contact support before recording another payout.');}});return()=>cancelAnimationFrame(frame);},[kind,storageKey]);
 function rejected(error:unknown){if(error instanceof RequestError&&error.code==='INSUFFICIENT_BALANCE'){sessionStorage.removeItem(storageKey);setPending(null);}}
 function completed(){router.push('/dashboard/admin?section='+({staff:'staff',payout:'payouts',grant:'grants'}[kind])+'&saved='+kind);router.refresh();}
 async function retryPayout(){if(!pending||running.current)return;running.current=true;setBusy(true);setError('');try{await requestJson('/api/admin/payouts',pending);sessionStorage.removeItem(storageKey);sessionStorage.removeItem('ga_pending_payout');setPending(null);completed();}catch(e){rejected(e);setError(e instanceof Error?e.message:'Could not confirm the saved payout.');}finally{running.current=false;setBusy(false);}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(running.current)return;const element=event.currentTarget;const values=new FormData(element);
  if(kind==='grant'&&!values.getAll('fields').length){const field=element.querySelector<HTMLInputElement>('input[name=fields]');field?.setCustomValidity('Select at least one field this employee may edit.');field?.reportValidity();return;}
  const recipient=event.currentTarget.querySelector<HTMLSelectElement>('select[name="profileId"]')?.selectedOptions[0]?.textContent||'Selected referrer';const form=new FormData(event.currentTarget);
  if(kind==='payout'&&!window.confirm(`Record ₹${form.get('amountRupees')} already paid to ${recipient}? This records an offline disbursement and reduces the available referral balance.`))return;
  running.current=true;setBusy(true);setError('');
  let body:Record<string,unknown>=Object.fromEntries(form);
  if(kind==='grant')body={employeeId:form.get('employeeId'),farmerId:form.get('farmerId'),reason:form.get('reason'),durationHours:form.get('durationHours'),fields:form.getAll('fields')};
  try{
   if(kind==='payout'){
    if(!ready||pending)throw new Error('Resolve the saved payout before entering another.');
    const key=sessionStorage.getItem('ga_pending_payout')||crypto.randomUUID();
    const payload=pendingPayoutSchema.parse({...body,idempotencyKey:key,recipientLabel:recipient});
    sessionStorage.setItem(storageKey,JSON.stringify(payload));setPending(payload);body=payload;
   }
   await requestJson('/api/admin/'+({staff:'staff',payout:'payouts',grant:'grants'}[kind]),body);
   if(kind==='payout'){sessionStorage.removeItem(storageKey);sessionStorage.removeItem('ga_pending_payout');setPending(null);}
   completed();
  }catch(e){rejected(e);setError(e instanceof Error?e.message:'Could not save this record. Your entries are retained; please try again.');if(e instanceof RequestError&&e.field){const input=element.elements.namedItem(e.field);if(input instanceof HTMLElement)input.focus();}}finally{running.current=false;setBusy(false);}
 }
 return <form className="admin-task-form" onSubmit={submit}>{error&&<p className="admin-alert error" role="alert">{error}</p>}{kind==='payout'&&pending&&<section role="status"><h2>Confirm saved payout</h2><p>A previous request may already be recorded. Retry the saved request to confirm its result. Do not disburse again.</p><p>₹{pending.amountRupees} · {pending.method} · {pending.reference||'No payment reference'} · {pending.recipientLabel||'Selected referrer'}</p><button className="admin-button" type="button" disabled={busy} onClick={()=>void retryPayout()}>{busy?'Checking…':'Retry saved payout record'}</button></section>}
 {kind==='staff'&&<section><h2>Account details</h2><p>Create access for an employee or manager.</p><div className="admin-form-grid"><label>Full name<PersonNameInput name="name" required minLength={2} maxLength={200} autoComplete="name"/></label><label>Mobile number<input name="mobile" onPaste={digitPaste} onBeforeInput={digitBeforeInput} inputMode="numeric" pattern="[0-9]{10}" minLength={10} maxLength={10} title="Enter exactly 10 digits; no spaces or country code." required autoComplete="tel-national"/></label><label>Temporary password<input name="password" type="password" minLength={8} maxLength={72} autoComplete="new-password" required/><small>At least 8 characters. The user can change it after signing in.</small></label><label>Role<select name="role"><option value="employee">Employee — own onboarded farmers</option><option value="manager">Manager — operations and edit access</option></select></label></div></section>}
 {kind==='payout'&&<><section><h2>Recipient</h2><p>Find the referrer and check their available balance.</p><AdminLookup name="profileId" kind="referrer" label="Referrer"/></section><section><h2>Disbursement details</h2><div className="admin-form-grid"><label>Amount (₹)<input name="amountRupees" type="number" min="0.01" max="1000000" step="0.01" required/></label><label>Method<select name="method"><option value="cash">Cash</option><option value="upi">UPI</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></select></label><label>Payment reference<input name="reference" maxLength={100}/></label><label>Note<input name="note" maxLength={300}/></label></div><label className="admin-check-label"><input type="checkbox" required/>I confirm this money has already been disbursed offline.</label><p className="admin-form-hint">This records the completed payout. It does not transfer money.</p></section></>}
 {kind==='grant'&&<><section><h2>Employee & farmer</h2><p>Select an employee, then a farmer they onboarded.</p><div className="admin-form-grid"><AdminLookup name="employeeId" kind="employee" label="Employee" onSelect={setEmployeeId}/><AdminLookup key={employeeId} name="farmerId" kind="farmer" label="Farmer" employeeId={employeeId}/></div></section><section><h2>Scope & expiry</h2><div className="admin-form-grid"><label>Duration (hours)<input name="durationHours" type="number" defaultValue={4} min={1} max={168} required/><small>Expires automatically. Maximum seven days.</small></label><label>Reason<input name="reason" minLength={3} maxLength={500} required/></label></div><fieldset className="admin-checkboxes" onChange={event=>event.currentTarget.querySelector<HTMLInputElement>("input[name=fields]")?.setCustomValidity("")}><legend>Fields this employee may edit</legend>{[['name','Name'],['date_of_birth','Date of birth'],['village','Village'],['district','District'],['taluka','Taluka'],['income_source','Income source'],['cluster_type','Cluster type']].map(([value,label])=><label className="admin-check-label" key={value}><input type="checkbox" name="fields" value={value}/>{label}</label>)}</fieldset></section></>}
 <div className="admin-form-footer"><button className="admin-button admin-button-secondary" type="button" disabled={busy} onClick={()=>router.push(adminHref({staff:'staff',payout:'payouts',grant:'grants'}[kind]))}>Cancel</button><button className="admin-button" disabled={busy||!ready||Boolean(pending)}>{busy?'Saving…':{staff:'Create team member',payout:'Record completed payout',grant:'Grant edit access'}[kind]}</button></div></form>;
}
