"use client";

import Script from "next/script";
import { useRouter } from "next/navigation";
import { useRef,useState,type FormEvent } from "react";
import { CLUSTER_OPTIONS,DISTRICTS,INCOME_OPTIONS,IRRIGATION_OPTIONS,TALUKAS,formatRupees } from "@/shared/constants";

declare global{interface Window{Razorpay?:new(options:Record<string,unknown>)=>{open():void}}}
type Plot={plot_no:string;area_acres:string;crop_name:string;irrigation_source:string};
type Saved={id:string;reference:string;amountPaise:number};
const emptyPlot=():Plot=>({plot_no:"",area_acres:"",crop_name:"",irrigation_source:""});
const incomeLabels:Record<string,string>={agriculture:"शेती / Agriculture",business:"व्यवसाय / Business",job:"नोकरी / Job",other:"इतर / Other"};
const clusterLabels:Record<string,string>={pulses:"कडधान्ये / Pulses",cereals:"तृणधान्ये / Cereals",cash:"नगदी पिके / Cash Crops",fruits:"फळे / Fruits",vegs:"भाजीपाला / Vegetables",allied:"संलग्न व्यवसाय / Allied Business"};
const irrigationLabels:Record<string,string>={well:"विहीर / Well",borewell:"कूपनलिका / Borewell",canal:"कालवा / Canal",drip:"ठिबक सिंचन / Drip",sprinkler:"तुषार सिंचन / Sprinkler",rainfed:"कोरडवाहू / Rainfed",river:"नदी / River",other:"इतर / Other"};

async function post<T>(url:string,body:unknown):Promise<T>{const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),15_000);try{const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:controller.signal});const result=await response.json() as T&{error?:string};if(!response.ok)throw new Error(result.error||"Request failed");return result}finally{window.clearTimeout(timer)}}

export function RegistrationForm({initialReferral,assisted,today}:{initialReferral:string;assisted:boolean;today:string}){
  const router=useRouter();const formTop=useRef<HTMLFormElement>(null);const[district,setDistrict]=useState("dharashiv");const[plots,setPlots]=useState<Plot[]>([emptyPlot()]);const[saved,setSaved]=useState<Saved|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[plotWarning,setPlotWarning]=useState("");const[cashReceived,setCashReceived]=useState(false);
  function updatePlot(index:number,key:keyof Plot,value:string){setPlots((all)=>all.map((plot,i)=>i===index?{...plot,[key]:value}:plot))}
  function addPlot(){if(plots.length>=10){setPlotWarning("कमाल १० प्लॉट जोडता येतील. / Maximum 10 plots allowed.");return}setPlotWarning("");setPlots((all)=>[...all,emptyPlot()])}
  function removePlot(index:number){if(plots.length===1){setPlotWarning("किमान एक प्लॉट आवश्यक आहे. / At least one plot is required.");return}setPlotWarning("");setPlots((all)=>all.filter((_,i)=>i!==index))}
  async function verify(orderId:string,paymentId:string,signature:string){const result=await post<{data:{receiptToken:string}}>("/api/payments/verify",{orderId,paymentId,signature,payerKind:cashReceived?"employee":"farmer"});router.push(`/receipt/${result.data.receiptToken}`)}
  async function startPayment(registration:Saved){setBusy(true);setError("");try{const result=await post<{data:{providerOrderId:string;amountPaise:number};demo?:boolean}>("/api/payments/orders",{registrationId:registration.id,reference:registration.reference,amountPaise:registration.amountPaise});if(result.demo){await verify(result.data.providerOrderId,`demo_payment_${crypto.randomUUID()}`,"demo");return}if(!window.Razorpay)throw new Error("Payment checkout is still loading. Please try again.");new window.Razorpay({key:process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,amount:result.data.amountPaise,currency:"INR",name:"Ganpati Agro Producer Company Ltd.",description:"Farmer membership fee",order_id:result.data.providerOrderId,theme:{color:"#1F6B3A"},handler:(value:unknown)=>{const payment=value as {razorpay_order_id:string;razorpay_payment_id:string;razorpay_signature:string};void verify(payment.razorpay_order_id,payment.razorpay_payment_id,payment.razorpay_signature).catch((reason)=>{setError(reason instanceof Error?reason.message:"Verification failed");setBusy(false)})},modal:{ondismiss:()=>setBusy(false)}}).open()}catch(reason){setError(reason instanceof DOMException&&reason.name==="AbortError"?"Request timed out. Please try again.":reason instanceof Error?reason.message:"Payment could not start");setBusy(false);formTop.current?.scrollIntoView({behavior:"smooth",block:"start"})}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;if(!form.checkValidity()){form.reportValidity();return}setBusy(true);setError("");const data=new FormData(form);if(data.get("password")!==data.get("confirm_password")){setError("पासवर्ड जुळत नाहीत. / Passwords do not match.");setBusy(false);return}try{const result=await post<{data:Saved}>("/api/registrations",{...Object.fromEntries(data),consent:data.get("consent")==="on",cash_received:data.get("cash_received")==="on",plots});setSaved(result.data);setBusy(false);await startPayment(result.data)}catch(reason){setError(reason instanceof DOMException&&reason.name==="AbortError"?"Request timed out. Please try again.":reason instanceof Error?reason.message:"Registration failed");setBusy(false);formTop.current?.scrollIntoView({behavior:"smooth",block:"start"})}}
  return <><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"/><form ref={formTop} className="legacy-registration-form" onSubmit={submit}>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <fieldset className="legacy-form-section"><legend><span className="legend-icon">♙</span>वैयक्तिक माहिती <em>Personal Details</em></legend>
      <div className="legacy-field"><label htmlFor="farmer-name">पूर्ण नाव <em>Full Name</em> <b>*</b></label><input id="farmer-name" name="name" required minLength={2} maxLength={200} placeholder="Enter full name" autoComplete="name"/></div>
      <div className="legacy-field-row"><div className="legacy-field"><label htmlFor="mobile">मोबाईल नंबर <em>Mobile Number</em> <b>*</b></label><input id="mobile" name="mobile" type="tel" required pattern="[0-9]{10}" maxLength={10} inputMode="numeric" placeholder="10-digit mobile number" autoComplete="tel"/></div><div className="legacy-field"><label htmlFor="dob">जन्मतारीख <em>Date of Birth</em> <b>*</b></label><input id="dob" name="date_of_birth" type="date" required max={today}/></div></div>
      <div className="legacy-field"><label htmlFor="aadhar">आधार क्रमांक <em>Aadhaar Number</em> <b>*</b></label><input id="aadhar" name="aadhar_no" required pattern="[0-9]{12}" maxLength={12} inputMode="numeric" placeholder="12-digit Aadhaar number" autoComplete="off"/></div>
      <div className="legacy-field-row"><div className="legacy-field"><label htmlFor="district">जिल्हा <em>District</em> <b>*</b></label><select id="district" name="district" value={district} onChange={(event)=>setDistrict(event.target.value)}>{DISTRICTS.map((item)=><option value={item.value} key={item.value}>{item.mr} / {item.en}</option>)}</select></div><div className="legacy-field"><label htmlFor="taluka">तालुका <em>Taluka</em> <b>*</b></label><select id="taluka" name="taluka" required defaultValue=""><option value="">तालुका निवडा / Select Taluka</option>{TALUKAS.filter((item)=>item[1]===district).map((item)=><option value={item[0]} key={item[0]}>{item[3]} / {item[2]}</option>)}</select></div></div>
      <div className="legacy-field"><label htmlFor="village">गाव <em>Village</em> <b>*</b></label><input id="village" name="village" required maxLength={200} placeholder="Enter village name"/></div>
      <div className="legacy-field"><span className="field-label">उत्पन्नाचे साधन <em>Income Source</em> <b>*</b></span><div className="radio-group">{INCOME_OPTIONS.map((value)=><label key={value}><input type="radio" name="income_source" value={value} required/><span>{incomeLabels[value]}</span></label>)}</div></div>
      <div className="legacy-field"><label htmlFor="cluster">समूह प्रकार <em>Cluster Type</em> <b>*</b></label><select id="cluster" name="cluster_type" required defaultValue=""><option value="">समूह प्रकार निवडा / Select Cluster Type</option>{CLUSTER_OPTIONS.map((value)=><option value={value} key={value}>{clusterLabels[value]}</option>)}</select></div>
    </fieldset>
    <fieldset className="legacy-form-section"><legend><span className="legend-icon">⌂</span>शेत माहिती <em>Farm Details</em></legend>{plots.map((plot,index)=><div className="farm-entry" key={index}><div className="farm-entry-head"><span>प्लॉट {index+1} / Plot {index+1}</span>{plots.length>1&&<button type="button" onClick={()=>removePlot(index)}>× Remove</button>}</div><div className="legacy-field-row"><div className="legacy-field"><label htmlFor={`plot-${index}`}>गट / सर्वे नंबर <em>Plot / Survey No.</em> <b>*</b></label><input id={`plot-${index}`} required maxLength={100} placeholder="e.g. 123/A" value={plot.plot_no} onChange={(event)=>updatePlot(index,"plot_no",event.target.value)}/></div><div className="legacy-field"><label htmlFor={`area-${index}`}>क्षेत्रफळ (एकर) <em>Area (Acres)</em> <b>*</b></label><input id={`area-${index}`} type="number" required min="0.01" max="100000" step="0.01" placeholder="e.g. 2.5" value={plot.area_acres} onChange={(event)=>updatePlot(index,"area_acres",event.target.value)}/></div></div><div className="legacy-field-row"><div className="legacy-field"><label htmlFor={`crop-${index}`}>पिकाचे नाव <em>Crop Name</em> <b>*</b></label><input id={`crop-${index}`} required maxLength={100} placeholder="e.g. Soybean" value={plot.crop_name} onChange={(event)=>updatePlot(index,"crop_name",event.target.value)}/></div><div className="legacy-field"><label htmlFor={`irrigation-${index}`}>सिंचन स्रोत <em>Irrigation Source</em> <b>*</b></label><select id={`irrigation-${index}`} required value={plot.irrigation_source} onChange={(event)=>updatePlot(index,"irrigation_source",event.target.value)}><option value="">स्रोत निवडा / Select Source</option>{IRRIGATION_OPTIONS.map((value)=><option value={value} key={value}>{irrigationLabels[value]}</option>)}</select></div></div></div>)}<button type="button" className="add-plot" onClick={addPlot}>＋ आणखी प्लॉट जोडा / Add Another Plot</button>{plotWarning&&<p className="plot-warning" role="status">{plotWarning}</p>}</fieldset>
    <fieldset className="legacy-form-section"><legend><span className="legend-icon">♢</span>लॉग इन आणि रेफरल <em>Account &amp; Referral</em></legend><div className="legacy-field-row"><div className="legacy-field"><label htmlFor="password">पासवर्ड <em>Password</em> <b>*</b></label><input id="password" name="password" type="password" required minLength={8} maxLength={128} placeholder="Minimum 8 characters" autoComplete="new-password"/></div><div className="legacy-field"><label htmlFor="confirm-password">पासवर्ड पुन्हा <em>Confirm Password</em> <b>*</b></label><input id="confirm-password" name="confirm_password" type="password" required minLength={8} maxLength={128} autoComplete="new-password"/></div></div><div className="legacy-field"><label htmlFor="referral">रेफरल कोड <em>Referral Code</em></label><input id="referral" name="referral_code" maxLength={16} defaultValue={initialReferral.toUpperCase()} readOnly={Boolean(initialReferral)} placeholder="Optional"/></div>{assisted&&<div className="cash-choice"><label><input name="cash_received" type="checkbox" checked={cashReceived} onChange={(event)=>setCashReceived(event.target.checked)}/><span><strong>कर्मचाऱ्याने रोख ₹५०० घेतले</strong><small>Employee keeps the cash and pays online from a personal account.</small></span></label>{cashReceived&&<div className="legacy-field"><label htmlFor="cash-note">Collection note <em>Optional</em></label><input id="cash-note" name="cash_note" maxLength={200} placeholder="Location or note"/></div>}</div>}</fieldset>
    <fieldset className="legacy-form-section consent-section"><legend><span className="legend-icon">◇</span>संमती व पेमेंट <em>Consent &amp; Payment</em></legend><div className="privacy-note">तुमची माहिती सभासदत्व, रेफरल आणि अधिकृत प्रशासकीय कामासाठीच वापरली जाईल. Aadhaar is protected and never shown in the dashboard.</div><div className="legacy-payment-summary"><span>सभासदत्व शुल्क / Membership fee</span><strong>{formatRupees(50_000)}</strong><small>Verified payment activates the membership immediately.</small></div><label className="legacy-consent"><input name="consent" type="checkbox" required/><span>मी दिलेली माहिती योग्य आहे आणि नोंदणी व सभासदत्वासाठी तिचा वापर करण्यास संमती देतो/देते. <b>*</b></span></label></fieldset>
    <input name="website" className="honeypot" tabIndex={-1} autoComplete="off"/>
    <button className="legacy-submit" disabled={busy} type="submit">{busy?<><span className="spinner"/>कृपया थांबा… / Please wait</>:<>नोंदणी करा आणि {formatRupees(50_000)} भरा</>}</button>{saved&&error&&<button type="button" className="retry-payment" onClick={()=>void startPayment(saved)}>Retry payment</button>}
  </form></>;
}
