"use client";

import {PersonNameInput} from "./PersonNameInput";
import {digitPaste,digitBeforeInput} from "@/shared/digit-input";
import {RequestError} from "@/shared/request";
import { PasswordToggle } from "./PasswordToggle";
import { VillageSearch } from './VillageSearch';
import { loadCheckout } from "@/features/payments/checkout-client";
import { useRouter } from "next/navigation";
import { useEffect,useRef,useState,type FormEvent } from "react";
import { CROP_CATEGORIES, CROP_LABELS, cropBelongsToCluster } from "@/shared/crop-catalog";
import { DISTRICTS,INCOME_OPTIONS,IRRIGATION_OPTIONS,TALUKAS,formatRupees } from "@/shared/constants";

import { requestJson as post } from "@/shared/request";

type Plot={plot_no:string;area_acres:string;crop_name:string;irrigation_source:string};
type Saved={id:string;reference:string;amountPaise:number;receiptToken?:string|null};
const emptyPlot=():Plot=>({plot_no:"",area_acres:"",crop_name:"",irrigation_source:""});
const incomeLabels:Record<string,string>={agriculture:"शेती / Agriculture",business:"व्यवसाय / Business",job:"नोकरी / Job",other:"इतर / Other"};
const irrigationLabels:Record<string,string>={well:"विहीर / Well",borewell:"कूपनलिका / Borewell",canal:"कालवा / Canal",drip:"ठिबक सिंचन / Drip",sprinkler:"तुषार सिंचन / Sprinkler",rainfed:"कोरडवाहू / Rainfed",river:"नदी / River",other:"इतर / Other"};

export function RegistrationForm({feePaise,initialReferral,today,hasCheckout=false}:{feePaise:number;initialReferral:string;today:string;hasCheckout?:boolean}){
  const [cluster,setCluster]=useState('');
  const [showPassword,setShowPassword]=useState(false);
  const [showConfirmation,setShowConfirmation]=useState(false);
  const crops=CROP_CATEGORIES.find(category=>category.id===cluster)?.crops ?? [];
  function changeCluster(value:string){setCluster(value);setPlots(all=>all.map(plot=>({...plot,crop_name:cropBelongsToCluster(value,plot.crop_name)?plot.crop_name:''})));}
  const router=useRouter();const formTop=useRef<HTMLFormElement>(null);const[mobile,setMobile]=useState("");const[password,setPassword]=useState("");const[confirmPassword,setConfirmPassword]=useState("");const[district,setDistrict]=useState("dharashiv");const[taluka,setTaluka]=useState("");const[village,setVillage]=useState("");const[plots,setPlots]=useState<Plot[]>([emptyPlot()]);const[saved,setSaved]=useState<Saved|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[plotWarning,setPlotWarning]=useState("");
  function updatePlot(index:number,key:keyof Plot,value:string){setPlots((all)=>all.map((plot,i)=>i===index?{...plot,[key]:value}:plot))}
  function addPlot(){if(plots.length>=10){setPlotWarning("कमाल १० प्लॉट जोडता येतील. / Maximum 10 plots allowed.");return}setPlotWarning("");setPlots((all)=>[...all,emptyPlot()])}
  function removePlot(index:number){if(plots.length===1){setPlotWarning("किमान एक प्लॉट आवश्यक आहे. / At least one plot is required.");return}setPlotWarning("");setPlots((all)=>all.filter((_,i)=>i!==index))}
  const inFlight=useRef(false);const [checking,setChecking]=useState(hasCheckout);const [status,setStatus]=useState("");
  useEffect(()=>{if(!hasCheckout)return;let active=true;post<{data:Saved|null}>("/api/payments/status",undefined,"GET").then(result=>{if(active){setSaved(result.data);setStatus(result.data?.receiptToken?"Payment successful. Open your receipt below.":result.data?"Registration restored. Check payment status before continuing.":"");}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Could not restore checkout.");}).finally(()=>{if(active)setChecking(false);});return()=>{active=false;};},[hasCheckout]);
  useEffect(()=>{if(saved&&!saved.receiptToken)void loadCheckout().catch(()=>{});},[saved]);
  useEffect(()=>{if(!busy||!status.startsWith('Payment received'))return;const timer=setTimeout(()=>setStatus('Verification is taking longer than usual. Please do not pay again.'),5000);return()=>clearTimeout(timer);},[busy,status]);
  async function checkStatus(){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');setStatus('Checking payment status…');try{const result=await post<{data:Saved}>('/api/payments/status',{});setSaved(result.data);setStatus(result.data.receiptToken?'Payment successful. Open your receipt below.':'Payment pending. If money was debited, do not pay again; check again or contact support.');}catch(reason){setError(reason instanceof Error?reason.message:'Verification unavailable. Do not pay again.');setStatus('Payment status uncertain. Reconnect and check payment status.');}finally{inFlight.current=false;setBusy(false);}}
  async function verify(orderId:string,paymentId:string,signature:string){setStatus('Payment received. Verifying…');performance.mark('ga.verify.start');try{const result=await post<{data:{receiptToken:string}}>('/api/payments/verify',{orderId,paymentId,signature});performance.mark('ga.verify.done');performance.measure('ga.verification','ga.verify.start','ga.verify.done');setSaved(current=>current?{...current,receiptToken:result.data.receiptToken}:current);setStatus('Payment successful. Opening receipt…');router.push('/receipt/'+result.data.receiptToken);}catch(reason){setError(reason instanceof Error?reason.message:'Verification unavailable. Do not pay again.');setStatus('Payment status uncertain. Use Check payment status before paying again.');}finally{inFlight.current=false;setBusy(false);}}
  async function startPayment(registration:Saved){
    if(inFlight.current)return;if(registration.receiptToken){router.push('/receipt/'+registration.receiptToken);return;}
    inFlight.current=true;setBusy(true);setError('');setStatus('Opening secure payment…');performance.mark('ga.pay.start');
    try{
      const [result]=await Promise.all([post<{data:{providerOrderId:string;amountPaise:number;keyId:string;demo?:boolean;receiptToken?:string}}>('/api/payments/orders',{registrationId:registration.id}),loadCheckout()]);
      performance.mark('ga.order.ready');performance.measure('ga.order-and-script','ga.pay.start','ga.order.ready');
      if(result.data.receiptToken){setSaved({...registration,receiptToken:result.data.receiptToken});router.push('/receipt/'+result.data.receiptToken);inFlight.current=false;setBusy(false);return;}
      if(result.data.demo){await verify(result.data.providerOrderId,'demo_payment_'+crypto.randomUUID(),'demo');return;}
      if(!window.Razorpay)throw new Error('Secure checkout unavailable. Please reconnect and continue.');
      let verifying=false;
      const checkout=new window.Razorpay({key:result.data.keyId,amount:result.data.amountPaise,currency:'INR',name:'Ganpati Agro Producer Company Ltd.',description:'Farmer membership fee',order_id:result.data.providerOrderId,theme:{color:'#1F6B3A'},handler:(value:unknown)=>{if(verifying)return;verifying=true;const payment=value as {razorpay_order_id:string;razorpay_payment_id:string;razorpay_signature:string};void verify(payment.razorpay_order_id,payment.razorpay_payment_id,payment.razorpay_signature);},modal:{ondismiss:()=>{if(!verifying){inFlight.current=false;setBusy(false);setStatus('Payment cancelled / checkout closed. If money was debited, check payment status before continuing.');}}}});
      checkout.on('payment.failed',()=>setStatus('Payment failed in checkout. Close it and check status if any amount was debited.'));
      checkout.open();performance.mark('ga.checkout.open');performance.measure('ga.checkout.launch','ga.pay.start','ga.checkout.open');setStatus('Payment in progress. Complete secure checkout or close it to return.');
    }catch(reason){setError(reason instanceof Error?reason.message:'Payment could not start.');setStatus('Payment status uncertain. Check status before trying again.');inFlight.current=false;setBusy(false);}
  }
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(checking||inFlight.current)return;if(saved){await startPayment(saved);return;}const form=event.currentTarget;if(!form.checkValidity()){form.reportValidity();return;}inFlight.current=true;setBusy(true);setError('');setStatus('Saving registration…');const data=new FormData(form);if(data.get('password')!==data.get('confirm_password')){setError('पासवर्ड जुळत नाहीत. / Passwords do not match.');setStatus('');inFlight.current=false;setBusy(false);form.querySelector<HTMLInputElement>('#confirm-password')?.focus();return;}
    try{const result=await post<{data:Saved}>('/api/registrations',{...Object.fromEntries(data),expected_fee_paise:feePaise,consent:data.get('consent')==='on',plots});
      const aadhar=form.elements.namedItem('aadhar_no');if(aadhar instanceof HTMLInputElement)aadhar.value='';setPassword('');setConfirmPassword('');
      setSaved(result.data);inFlight.current=false;await startPayment(result.data);form.scrollIntoView({block:'start',behavior:'instant'});
    }catch(reason){setError(reason instanceof Error?reason.message:'Registration failed.');setStatus('Registration could not be confirmed. Reconnect and retry with the same details to resume safely.');if(reason instanceof RequestError&&reason.field){const field=form.elements.namedItem(reason.field);if(field instanceof HTMLElement)field.focus();}inFlight.current=false;setBusy(false);}
  }
  return <><form ref={formTop} className="legacy-registration-form" onSubmit={submit}>
    {saved&&<section className="checkout-summary"><span className="eyebrow">सभासदत्व / Membership</span><h2>{saved.receiptToken?'Payment successful':'Secure payment'}</h2><strong>{formatRupees(saved.amountPaise)}</strong><p>Registration {saved.reference}</p><small>पेमेंट पूर्ण झाल्यावर सभासदत्व सक्रिय होईल. / Membership activates after successful payment.</small></section>}{error&&<p className="form-error" role="alert">{error}</p>}{(status||checking)&&<p className="payment-status" role="status" aria-live="polite">{checking?'Checking saved registration…':status}</p>}
    <fieldset hidden={Boolean(saved)} disabled={busy||checking||Boolean(saved)} className="legacy-form-section"><legend>वैयक्तिक माहिती <em>Personal Details</em></legend>
      <div className="legacy-field"><label htmlFor="farmer-name">पूर्ण नाव <em>Full Name</em> <b>*</b></label><PersonNameInput id="farmer-name" name="name" required minLength={2} maxLength={200} placeholder="Enter full name" autoComplete="name"/></div>
      <div className="legacy-field-row"><div className="legacy-field"><label htmlFor="mobile">मोबाईल नंबर <em>Mobile Number</em> <b>*</b></label><input id="mobile" name="mobile" onPaste={digitPaste} onBeforeInput={digitBeforeInput} type="tel" required pattern="[0-9]{10}" minLength={10} maxLength={10} title="Enter exactly 10 digits; no spaces or country code." inputMode="numeric" placeholder="10-digit mobile number" autoComplete="tel" value={mobile} onChange={event=>setMobile(event.target.value)}/></div><div className="legacy-field"><label htmlFor="dob">जन्मतारीख <em>Date of Birth</em> <b>*</b></label><input id="dob" name="date_of_birth" type="date" required max={today}/></div></div>
      <div className="legacy-field"><label htmlFor="aadhar">आधार क्रमांक <em>Aadhaar Number</em> <b>*</b></label><input id="aadhar" name="aadhar_no" onPaste={digitPaste} onBeforeInput={digitBeforeInput} required pattern="[0-9]{12}" minLength={12} maxLength={12} title="Enter exactly 12 digits; no spaces or punctuation." inputMode="numeric" placeholder="12-digit Aadhaar number" autoComplete="off"/></div>
      <div className="legacy-field-row"><div className="legacy-field"><label htmlFor="district">जिल्हा <em>District</em> <b>*</b></label><select id="district" name="district" value={district} onChange={(event)=>{setDistrict(event.target.value);setTaluka("");setVillage("");}}>{DISTRICTS.map((item)=><option value={item.value} key={item.value}>{item.mr} / {item.en}</option>)}</select></div><div className="legacy-field"><label htmlFor="taluka">तालुका <em>Taluka</em> <b>*</b></label><select id="taluka" name="taluka" required value={taluka} onChange={event=>{setTaluka(event.target.value);setVillage("");}}><option value="">तालुका निवडा / Select Taluka</option>{TALUKAS.filter((item)=>item[1]===district).map((item)=><option value={item[0]} key={item[0]}>{item[3]} / {item[2]}</option>)}</select></div></div>
      <div className="legacy-field"><VillageSearch key={taluka} taluka={taluka} value={village} onChange={setVillage}/></div>
      <div className="legacy-field"><span className="field-label">उत्पन्नाचे साधन <em>Income Source</em> <b>*</b></span><div className="radio-group">{INCOME_OPTIONS.map((value)=><label key={value}><input type="radio" name="income_source" value={value} required/><span>{incomeLabels[value]}</span></label>)}</div></div>
    </fieldset>
    <fieldset hidden={Boolean(saved)} disabled={busy||checking||Boolean(saved)} className="legacy-form-section"><legend>शेत माहिती <em>Farm Details</em></legend><div className="legacy-field"><label htmlFor="cluster">समूह प्रकार <em>Cluster Type</em> <b>*</b></label><select id="cluster" name="cluster_type" required value={cluster} onChange={event=>changeCluster(event.target.value)}><option value="">समूह प्रकार निवडा / Select Cluster Type</option>{CROP_CATEGORIES.map((category)=><option value={category.id} key={category.id}>{category.label}</option>)}</select></div>{plots.map((plot,index)=><div className="farm-entry" key={index}><div className="farm-entry-head"><span>प्लॉट {index+1} / Plot {index+1}</span>{plots.length>1&&<button type="button" onClick={()=>removePlot(index)}>× Remove</button>}</div><div className="legacy-field-row"><div className="legacy-field"><label htmlFor={`plot-${index}`}>गट / सर्वे नंबर <em>Plot / Survey No.</em> <b>*</b></label><input id={`plot-${index}`} required maxLength={100} placeholder="e.g. 123/A" value={plot.plot_no} onChange={(event)=>updatePlot(index,"plot_no",event.target.value)}/></div><div className="legacy-field"><label htmlFor={`area-${index}`}>क्षेत्रफळ (एकर) <em>Area (Acres)</em> <b>*</b></label><input id={`area-${index}`} type="number" inputMode="decimal" required min="0.01" max="100000" step="0.01" placeholder="e.g. 2.5" value={plot.area_acres} onChange={(event)=>updatePlot(index,"area_acres",event.target.value)}/></div></div><div className="legacy-field-row"><div className="legacy-field"><label htmlFor={`crop-${index}`}>पिकाचे नाव <em>Crop Name</em> <b>*</b></label><select id={`crop-${index}`} required disabled={!cluster} value={plot.crop_name} onChange={(event)=>updatePlot(index,"crop_name",event.target.value)}><option value="">{cluster?"पीक निवडा / Select Crop":"आधी समूह निवडा / Select cluster first"}</option>{crops.map(crop=><option key={crop} value={crop}>{CROP_LABELS[crop]}</option>)}</select></div><div className="legacy-field"><label htmlFor={`irrigation-${index}`}>सिंचन स्रोत <em>Irrigation Source</em> <b>*</b></label><select id={`irrigation-${index}`} required value={plot.irrigation_source} onChange={(event)=>updatePlot(index,"irrigation_source",event.target.value)}><option value="">स्रोत निवडा / Select Source</option>{IRRIGATION_OPTIONS.map((value)=><option value={value} key={value}>{irrigationLabels[value]}</option>)}</select></div></div></div>)}<button type="button" className="add-plot" onClick={addPlot}>＋ आणखी प्लॉट जोडा / Add Another Plot</button>{plotWarning&&<p className="plot-warning" role="status">{plotWarning}</p>}</fieldset>
    <fieldset hidden={Boolean(saved)} disabled={busy||checking||Boolean(saved)} className="legacy-form-section"><legend>लॉग इन आणि रेफरल <em>Account &amp; Referral</em></legend><div className="legacy-field-row"><div className="legacy-field"><label htmlFor="password">पासवर्ड <em>Password</em> <b>*</b></label><div className="password-control"><input id="password" name="password" type={showPassword?"text":"password"} required minLength={8} maxLength={72} placeholder="At least 8 characters" aria-describedby="password-help" autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)}/><PasswordToggle visible={showPassword} onToggle={()=>setShowPassword(value=>!value)} inputId="password"/></div></div><div className="legacy-field"><label htmlFor="confirm-password">पासवर्ड पुन्हा <em>Confirm Password</em> <b>*</b></label><div className="password-control"><input id="confirm-password" name="confirm_password" type={showConfirmation?"text":"password"} required minLength={8} maxLength={72} autoComplete="new-password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)}/><PasswordToggle visible={showConfirmation} onToggle={()=>setShowConfirmation(value=>!value)} inputId="confirm-password"/></div></div></div><p id="password-help" className="field-help">किमान ८ अक्षरांचा पासवर्ड वापरा. / Use at least 8 characters.</p><div className="legacy-field"><label htmlFor="referral">रेफरल कोड <em>Referral Code</em></label><input id="referral" name="referral_code" maxLength={16} defaultValue={initialReferral.toUpperCase()} pattern="[A-Za-z0-9]{6,16}" title="Use 6–16 letters or digits, or leave blank." placeholder="Optional"/></div></fieldset>
    <fieldset hidden={Boolean(saved)} disabled={busy||checking||Boolean(saved)} className="legacy-form-section consent-section"><legend>संमती व पेमेंट <em>Consent &amp; Payment</em></legend><div className="privacy-note">तुमची माहिती नोंदणी, सभासदत्व आणि रेफरल सेवांसाठी वापरली जाईल. / Your information will be used for registration, membership and referral services.</div><div className="legacy-payment-summary"><span>सभासदत्व शुल्क / Membership fee</span><strong>{formatRupees(feePaise)}</strong><small>पेमेंट पूर्ण झाल्यावर सभासदत्व सक्रिय होईल. / Membership activates after successful payment.</small></div><label className="legacy-consent"><input name="consent" type="checkbox" required/><span>मी दिलेली माहिती योग्य आहे आणि नोंदणी व सभासदत्वासाठी तिचा वापर करण्यास संमती देतो/देते. <b>*</b></span></label></fieldset>
    <input name="website" className="honeypot" aria-hidden="true" tabIndex={-1} autoComplete="off"/>
    <button className="legacy-submit" disabled={busy||checking} type="submit">{busy?<><span className="spinner"/> {status.startsWith("Opening")?"Opening payment…":status.startsWith("Saving")?"Saving registration…":status.startsWith("Checking")?"Checking payment…":"Payment in progress…"}</>:saved?(saved.receiptToken?"Open payment receipt":"Continue to secure payment"):"नोंदणी करा"}</button>
    {saved&&<button type="button" className="retry-payment" disabled={busy||checking} onClick={()=>void checkStatus()}>Check payment status / पेमेंट तपासा</button>}
    {saved?.receiptToken&&<button type="button" className="retry-payment" disabled={busy} onClick={()=>{void post("/api/payments/status",undefined,"DELETE").then(()=>{setSaved(null);formTop.current?.reset();setMobile("");setPassword("");setConfirmPassword("");setCluster("");setShowPassword(false);setShowConfirmation(false);setDistrict("dharashiv");setTaluka("");setVillage("");setPlots([emptyPlot()]);setStatus("");}).catch(reason=>setError(reason instanceof Error?reason.message:"Could not start another registration."));}}>Start another registration</button>}

  </form></>;
}
